#spring.application.name=aulao-spring-security


spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "966315057786-fokgnb6oa56qnk1sagi70mosb22hjrf6.apps.googleusercontent.com"
            client-secret: { {"CHAVE" } }
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com